---
downloads: ~/.ansible-downloads/

configure_dotfiles: yes
configure_sudoers: no
configure_terminal: no
configure_osx: no

dotfiles_repo: git@github.com:aSapien/dotfiles.git
dotfiles_repo_accept_hostkey: yes
dotfiles_repo_local_destination: ~/projects/dotfiles
dotfiles_files:
  - .gitignore
  - .gitconfig
  - .skhdrc
  - .yabairc
  - .localconfig.fish

homebrew_installed_packages:
  # - ansible # Installed via Pip.
  - ammonite-repl # Scala REPL
  - autojump      # Filesystem navigation
  - bat           # A better alrernative to `cat`, with syntax, etc.
  - bitwarden-cli # Password manager CLI
  - dive          # Docker image explorer
  - exa           # Colorized `ls`
  - fd            # A better alternative to `find` 
  - fish          # Fish shell
  - fzf           # Fuzzy Filesystem navigation
  - git
  - git-delta     # Terminal Diff for git
  - go
  - hashicorp/tap/terraform # Terraform
  - hugo          # Static site generator
  - httpie        # Like cURL but with colored output
  - iproute2mac   # iproute2 instead of net-tools (ip instead of ifconfig)
  - jq            # json maniulations for the terminal
  - kafka
  - koekeishiya/formulae/skhd          # A hotkey daemon, complemetary to `yabai`
  - koekeishiya/formulae/yabai         # MacOS Tiling window manager
  - kubectx       # Easy switch between K8s contexts and namespaces
  - mas           # Mac App Store - CLI
  - openssl
  - poetry        # Python environment management
  - scala
  - scc           # A tool similar to cloc & loc. For counting lines of code, blank, etc, by language.
  - ssh-copy-id   # copy public key to remote machine's authorized_keys
  - tldr          # Explain commands and common
  - tmux          # Terminal multiplexer
  - tree          # View directory tree
  - watch         # Watch for changes in output for a repeatedly executed command
  - wget          

homebrew_taps:
  - homebrew/core
  - homebrew/cask
  - homebrew/cask-versions
  - hashicorp/tap

homebrew_cask_appdir: /Applications
homebrew_cask_apps:
  - homebrew/cask-versions/adoptopenjdk8
  - alfred
  - bitwarden
  - dash
  - docker
  - flux
  - google-cloud-sdk
  - grandperspective      # Free/Occupied Space Disk Visualizer
  - hammerspoon           # MacOS Lua automation scripting
  - jetbrains-toolbox
  - iterm2
  - karabiner-elements
  - kindle
  - lens # K8s IDE based on Electron
  - ngrok
  - notion
  - odrive
  - paw
  - protonvpn
  - slack
  - spotify
  - steam
  - stremio
  - telegram
  - the-unarchiver
  - vagrant
  - virtualbox
  - virtualbox-extension-pack
  - visual-studio-code
  - vlc
  - wireshark
  - zoom

# See `geerlingguy.mas` role documentation for usage instructions.
mas_installed_apps: []
mas_email: ""
mas_password: ""

osx_script: "~/.osx --no-restart"

# Install packages from other package managers.
# Note: You are responsible for making sure the required package managers are
# installed, eg. through homebrew.
composer_packages: []
  # - name: drush
  #   state: present # present/absent, default: present
  #   version: "^8.1" # default: N/A
gem_packages: []
  # - name: bundler
  #   state: present # present/absent/latest, default: present
  #   version: "~> 1.15.1" # default: N/A
npm_packages: []
  # - name: webpack
  #   state: present # present/absent/latest, default: present
  #   version: "^2.6" # default: N/A
pip_packages: 
  - name: graphtage
  # - name: mkdocs
  #   state: present # present/absent/latest, default: present
  #   version: "0.16.3" # default: N/A

# Glob pattern to ansible task files to run after all other tasks are finished.
post_provision_tasks: []
